apiVersion: v2
name: ${{ values.name }}
description: ${{ values.description }}
version: 0.1.0
appVersion: "latest"
type: application
keywords:
  - llm
  - ai
  - gateway
  - litellm
home: https://github.com/bd-core-svcs/${{ values.name }}
sources:
  - https://github.com/bd-core-svcs/${{ values.name }}
maintainers:
  - name: ${{ values.owner }}
    email: ${{ values.owner }}
