apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-service-migration
  title: Python Migration (Cross-Organization)
  description: Migrate an existing Python service repository from one GitHub organization to another with Python-specific CI/CD setup
  tags:
    - migration
    - cross-org
    - repository
    - github
    - python
    - llm-service
    - ci-cd
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: blackduck-common/platform-devportal
spec:
  type: migration
  owner: platform-team
  parameters:
    - title: Migration Information
      properties:
        techStack:
          title: Tech Stack
          type: string
          description: Technology stack for this migration
          default: 'Python'
          enum:
            - 'Python'
          ui:readonly: true
          ui:help: 'This template is specifically for Python repository migrations'
    
    - title: Source Repository Information
      required:
        - sourceRepoUrl
        - description
        - owner
      properties:
        sourceRepoUrl:
          title: Source Repository URL
          type: string
          description: The GitHub repository URL to migrate from (e.g., https://github.com/SIG-Innovation-Zone/service-llm)
          pattern: '^https://github\.com/[^/]+/[^/]+/?$'
          ui:autofocus: true
          ui:help: 'Full GitHub repository URL including https://github.com/'
        description:
          title: Description
          type: string
          description: Description of the Python service being migrated
          default: 'Migration from SIG-Innovation-Zone'
        owner:
          title: Owner
          type: string
          description: Owner of the migrated service
          default: 'platform-team'

    - title: Destination Repository Information
      required:
        - destinationRepoUrl
      properties:
        destinationRepoUrl:
          title: Destination Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOrganizations:
              - bd-polaris
              - bd-core-svcs
              - blackduck-common

    - title: Migration Configuration
      properties:
        projectType:
          title: Project Type
          type: string
          description: Type of Python project being migrated
          default: 'python-service'
          enum:
            - 'python-service'
            - 'llm-gateway'
            - 'api-service'
            - 'ml-service'
            - 'data-service'
            - 'web-service'
            - 'other'
        addDockerfile:
          title: Add Dockerfile
          type: boolean
          description: Generate Dockerfile if not present in source repository
          default: true
        addGitHubWorkflow:
          title: Add GitHub Workflow
          type: boolean
          description: Add CI/CD GitHub Actions workflow
          default: true
        createArgoCDConfig:
          title: Create ArgoCD Configuration
          type: boolean
          description: Create ArgoCD configuration for deployment
          default: true
        migrationNote:
          title: Migration Notes
          type: string
          description: Additional notes about this migration (optional)
          ui:widget: textarea

  steps:
    - id: fetch-source
      name: Fetch Source Repository
      action: fetch:template
      input:
        url: ${{ parameters.sourceRepoUrl }}
        targetPath: '.'
        # Copy all files from source repository without template processing
        copyWithoutRender: 
          - '**/*'
        # Use GitHub integration for SIG-Innovation-Zone
        # The GitHub App bd-migration-reader handles authentication automatically

    - id: create-catalog-info
      name: Create catalog-info.yaml for Python service
      action: catalog:write
      input:
        filePath: 'catalog-info.yaml'
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.destinationRepoUrl | parseRepoUrl | pick('repo') }}
            description: ${{ parameters.description }}
            annotations:
              github.com/project-slug: ${{ parameters.destinationRepoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.destinationRepoUrl | parseRepoUrl | pick('repo') }}
          spec:
            type: service
            lifecycle: experimental
            owner: ${{ parameters.owner }}

    - id: publish
      name: Create and Publish to Destination
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'Migrated Python service from ${{ parameters.sourceRepoUrl }} - ${{ parameters.description }}'
        repoUrl: ${{ parameters.destinationRepoUrl }}
        defaultBranch: main
        gitCommitMessage: 'Initial migration from ${{ parameters.sourceRepoUrl }}'
        gitAuthorName: 'Backstage Migration'
        gitAuthorEmail: 'migration@backstage.io'
        topics:
          - migrated
          - ${{ parameters.projectType }}
          - backstage-migrated

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        optional: true

    - id: fetch-argocd-config
      name: Fetch ArgoCD Config Templates
      condition: ${{ parameters.createArgoCDConfig }}
      action: fetch:template
      input:
        url: ./argocd-config
        targetPath: 'argocd-config'
        values:
          name: ${{ parameters.destinationRepoUrl | parseRepoUrl | pick('repo') }}

    - id: create-argocd-config-pr
      name: Create ArgoCD Configuration PR
      condition: ${{ parameters.createArgoCDConfig }}
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        description: 'Add ArgoCD configuration for migrated service ${{ parameters.destinationRepoUrl | parseRepoUrl | pick("repo") }}'
        repoUrl: 'github.com?owner=bd-polaris&repo=argo-config'
        branchName: 'add-argocd-config-${{ parameters.destinationRepoUrl | parseRepoUrl | pick("repo") }}'
        title: 'Add ArgoCD configuration for ${{ parameters.destinationRepoUrl | parseRepoUrl | pick("repo") }} (migrated)'
        sourcePath: 'argocd-config'
        targetPath: '${{ parameters.destinationRepoUrl | parseRepoUrl | pick("repo") }}'

    - id: migration-summary
      name: Migration Summary
      action: debug:log
      input:
        message: |
          🎉 Python Service migration completed successfully!
          
          ✅ **Migration Details:**
          - **Source**: ${{ parameters.sourceRepoUrl }}
          - **Destination**: ${{ steps.publish.output.remoteUrl }}
          - **Service Type**: ${{ parameters.serviceType }}
          - **Python Version**: ${{ parameters.pythonVersion }}
          - **Framework**: ${{ parameters.framework }}
          
          ✅ **What was created:**
          1. **Migrated Repository**: ${{ steps.publish.output.remoteUrl }}
          2. **ArgoCD Configuration PR**: Check `bd-polaris/argo-config` for PR (if enabled)
          3. **Python GitHub Workflow**: CI/CD pipeline added (if enabled)
          4. **Updated Dockerfile**: Configured for new organization (if enabled)
          5. **Database Support**: PostgreSQL/Redis configurations preserved (if detected)
          6. **Documentation**: MkDocs setup maintained (if detected)
          
          ✅ **Python Service Features:**
          - ✅ Complete source code migration
          - ✅ Python-specific CI/CD pipeline
          - ✅ Container support with updated Dockerfile
          - ✅ ArgoCD deployment configuration
          - ✅ Database and Redis configurations preserved
          - ✅ Documentation setup maintained
          
          ⚠️ **Important Notes:**
          - Source repository remains unchanged
          - Review and customize generated files as needed
          - Update environment variables for new organization
          - Merge ArgoCD configuration PR to enable deployment
          - Update any hardcoded references to new organization
          - Verify database connection strings and Redis configurations
          
          📝 **Migration Notes:**
          ${{ parameters.migrationNotes || "No additional notes provided" }}

  output:
    links:
      - title: Migrated Python Service Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Source Repository
        url: ${{ parameters.sourceRepoUrl }}
      - title: View ArgoCD Config PR
        url: 'https://github.com/bd-core-svcs/argo-config/pulls'