name: ${{ values.name }}
on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/736458129177/locations/global/workloadIdentityPools/github-actions-pool-v1alpha1/providers/github-provider-v1alpha1
          service_account: sa-gha-core-svcs@sig-innovation-zone-prd.iam.gserviceaccount.com

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: |
            us-docker.pkg.dev/cloudops-artifacts-prd/core-svcs/${{ values.name }}-poc-idp:latest
            us-docker.pkg.dev/cloudops-artifacts-prd/core-svcs/${{ values.name }}-poc-idp:${{ '${{ github.sha }}' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
