name: ${{ values.component_id }}
on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  repository_dispatch:
    types: [build]
  schedule:
    - cron: '0 6 * * 0' # 6am UTC = 11pm PST / 11:30 IST on Sundays redeploy to stay up to date with main:latest

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/736458129177/locations/global/workloadIdentityPools/github-actions-pool-v1alpha1/providers/github-provider-v1alpha1
          service_account: sa-gha-core-svcs@sig-innovation-zone-prd.iam.gserviceaccount.com

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: us-docker.pkg.dev/cloudops-artifacts-prd/core-svcs/${{ values.component_id }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
