replicaCount: 1

image:
  repository: us-docker.pkg.dev/cloudops-artifacts-prd/core-svcs/${{ values.name }}
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "gce-internal"
  annotations:
    kubernetes.io/ingress.class: gce-internal
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: ${{ values.name }}.dev.svc.gcp.blackduck.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Health Probes for Python services
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 15
  periodSeconds: 5