apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${{ values.name }}.fullname" . }}
  labels:
    {{- include "${{ values.name }}.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "${{ values.name }}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "${{ values.name }}.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "${{ values.name }}.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.config.environment | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: litellm-master-key
            - name: AZURE_API_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: azure-api-base
            - name: AZURE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: azure-api-key
            - name: AZURE_API_VERSION
              value: {{ .Values.config.azure.apiVersion | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: aws-secret-access-key
            - name: AWS_REGION
              value: {{ .Values.config.aws.region | quote }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: openai-api-key
{%- if values.enablePostgreSQL %}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-secrets
                  key: database-url
{%- endif %}
{%- if values.enableRedis %}
            - name: REDIS_HOST
              value: {{ include "${{ values.name }}.fullname" . }}-redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "${{ values.name }}.fullname" . }}-redis
                  key: redis-password
{%- endif %}
          volumeMounts:
            - name: config
              mountPath: /app/litellm-config.yaml
              subPath: litellm-config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "${{ values.name }}.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
