apiVersion: v1
kind: Secret
metadata:
  name: {{ include "${{ values.name }}.fullname" . }}-secrets
  labels:
    {{- include "${{ values.name }}.labels" . | nindent 4 }}
type: Opaque
data:
  litellm-master-key: {{ .Values.config.litellm.masterKey | b64enc | quote }}
  azure-api-base: {{ .Values.config.azure.apiBase | b64enc | quote }}
  azure-api-key: {{ .Values.config.azure.apiKey | b64enc | quote }}
  aws-access-key-id: {{ .Values.config.aws.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.config.aws.secretAccessKey | b64enc | quote }}
  openai-api-key: {{ .Values.config.openai.apiKey | b64enc | quote }}
  {{- if and .Values.postgresql .Values.postgresql.enabled }}
  database-url: {{ printf "postgresql://postgres:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.postgresPassword (include "${{ values.name }}.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
