apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-config
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  app-config.production.yaml: |
{{ .Files.Get "app-config.production.yaml" | indent 4 }}
