apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backstage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backstage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backstage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.config.environment | quote }}
            - name: POSTGRES_HOST
              value: {{ include "backstage.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-postgresql
                  key: postgres-password
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-client-secret
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-token
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-app-id
            - name: GITHUB_APP_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-app-installation-id
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backstage.fullname" . }}-secrets
                  key: github-app-private-key
            - name: AWS_ACCOUNT_ID
              value: {{ .Values.config.aws.accountId | quote }}
            - name: AWS_REGION
              value: {{ .Values.config.aws.region | quote }}
            - name: TECHDOCS_S3_BUCKET_NAME
              value: {{ .Values.config.techdocs.s3BucketName | quote }}
            - name: EKS_CLUSTER_URL
              value: "https://$(aws eks describe-cluster --name sig-saas-innovation-zone --region us-east-1 --query 'cluster.endpoint' --output text)"
          volumeMounts:
            - name: app-config
              mountPath: /app/app-config.production.yaml
              subPath: app-config.production.yaml
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: {{ include "backstage.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
